name: Build Tidal-GUI

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Tidal-Media-Downloader
      uses: actions/checkout@v4
      with:
        path: Tidal-Media-Downloader-PRO
        
    - name: Checkout AIGS
      uses: actions/checkout@v4
      with:
        repository: AIGMix/AIGS
        path: AIGS
        
    - name: Checkout TidalLib
      uses: actions/checkout@v4
      with:
        repository: yaronzz/TidalLib
        path: TidalLib

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore AIGS
      run: nuget restore AIGS\AIGS.sln
      
    - name: Build AIGS
      run: msbuild AIGS\AIGS.sln /p:Configuration=Debug

    - name: Restore TidalLib
      run: nuget restore TidalLib\TidalLib\TidalLib.sln
      
    - name: Build TidalLib
      run: msbuild TidalLib\TidalLib\TidalLib.sln /p:Configuration=Debug

    - name: Restore Tidal-GUI
      run: |
        $sln = Get-ChildItem -Path Tidal-Media-Downloader-PRO -Filter TIDALDL-UI.sln -Recurse | Select-Object -ExpandProperty FullName
        nuget restore $sln
      
    - name: Build Tidal-GUI
      run: |
        $sln = Get-ChildItem -Path Tidal-Media-Downloader-PRO -Filter TIDALDL-UI.sln -Recurse | Select-Object -ExpandProperty FullName
        msbuild $sln /p:Configuration=Release

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: tidal-gui-app
        path: Tidal-Media-Downloader-PRO\**\bin\Release\
